plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'com.gradleup.shadow' version '9.6.1'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url 'https://jitpack.io' }
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	shadow(implementation("org.apache.commons:commons-math3:3.6.1"))

	String nfdVersion = "org.lwjgl:lwjgl-nfd:3.3.3"

	shadow(implementation(nfdVersion) {
		exclude group: 'org.lwjgl'
		exclude group: 'org.lwjgl.lwjgl'
	})
	shadow(api("org.lwjgl:lwjgl-nfd::natives-macos") {
		exclude group: 'org.lwjgl'
		exclude group: 'org.lwjgl.lwjgl'
	})
	shadow(api("org.lwjgl:lwjgl-nfd::natives-linux") {
		exclude group: 'org.lwjgl'
		exclude group: 'org.lwjgl.lwjgl'
	})
	shadow(api("org.lwjgl:lwjgl-nfd::natives-windows") {
		exclude group: 'org.lwjgl'
		exclude group: 'org.lwjgl.lwjgl'
	})
	shadow(api("org.lwjgl:lwjgl-nfd::natives-macos-arm64") {
		exclude group: 'org.lwjgl'
		exclude group: 'org.lwjgl.lwjgl'
	})
	shadow(api("org.lwjgl:lwjgl-nfd::natives-linux-arm64") {
		exclude group: 'org.lwjgl'
		exclude group: 'org.lwjgl.lwjgl'
	})
	shadow(api("org.lwjgl:lwjgl-nfd::natives-windows-arm64") {
		exclude group: 'org.lwjgl'
		exclude group: 'org.lwjgl.lwjgl'
	})
}

processResources {
	def version = project.version
	inputs.property "version", version
	inputs.property "minecraft_version", project.minecraft_version
	inputs.property "loader_version", project.loader_version
	filteringCharset "UTF-8"

	filesMatching("fabric.mod.json") {
		expand "version": version,
				"minecraft_version": project.minecraft_version,
				"loader_version": project.loader_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	withSourcesJar()
}

shadowJar {
	configurations = [project.configurations.shadow]
	archiveClassifier.set('')
}

jar {
	enabled = false
	dependsOn shadowJar
}

shadowJar.finalizedBy(tasks.named('sourcesJar'))

tasks.named('assemble') {
	dependsOn shadowJar
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
	}
}
